
actor User
component "jpa-entity-generator" as JEG
database DB
file "jeg-config.yml" as config
file "JpaEntitiy.java" as src

User -> JEG : 1. java -jar jpa-entity-generator-core.jar\n./mvnw jpa-entity-generator:reverse
JEG -up-> config: 2. read
JEG -> DB: 3. read DB metadata
JEG --> src: 4. write
