runtime:
  jdbcUrl: "${db.jdbc.url}"
  jdbcUsername: "${db.username}"
  jdbcPassword: "${db.password}"
  outputDir: "${jeg.outputDir}"
  metadataOutputDir: "${jeg.outputDir}"
schemaPattern: ${db.schema}
packages:
  dev.aulait.jeg.core.domain.mastertran:
    - master
    - transaction
    - composite_master
    - composite_transaction
    - field_name_transaction
  dev.aulait.jeg.core.domain.parentchild:
    - parent
    - child
    - composite_parent
    - composite_child
  dev.aulait.jeg.core.domain.multifk:
    - multifk_parent
    - multifk_child
  dev.aulait.jeg.core.domain.manytomany:
    - left
    - right
  dev.aulait.jeg.core.domain.datatypes:
    - data_types
    - data_types_nonull
  dev.aulait.jeg.core.domain.selfref:
    - self_reference
    - composite_self_reference
  dev.aulait.jeg.core.domain.autoincrement:
    - auto_increment
  dev.aulait.jeg.core.domain.bridge:
    - west
    - east
    - west_east_bridge
    - composite_west
    - composite_east
    - composite_west_east_bridge
  dev.aulait.jeg.core.domain.cascadeonetomany:
    - cascade_onetomany_parent
    - cascade_onetomany_child
  dev.aulait.jeg.core.domain.readonlymanytoone:
    - readonly_manytoone_master
    - readonly_manytoone_transaction
    - composite_readonly_manytoone_master
    - composite_readonly_manytoone_transaction
baseClassDefs:
  - tables:
      - composite_master
      - composite_parent
      - composite_child
      - composite_self_reference
      - composite_readonly_manytoone_master
    baseClass: dev.aulait.jeg.core.domain.CompositeBaseEntity
  - tables:
      - "*"
    baseClass: dev.aulait.jeg.core.domain.BaseEntity
annotationDefs:
  uuid:
    type: jakarta.persistence.GeneratedValue
    attributes:
      strategy: jakarta.persistence.GenerationType.UUID
  noEffect:
    type: lombok.Setter
excludedTables:
  - flyway_schema_history
excludedColumns:
  - version
  - created_by
  - created_date
  - updated_by
  - updated_date
cascadeOneToMany:
  - cascade_onetomany_parent.cascade_onetomany_child
readonlyManyToOne:
  - readonly_manytoone_transaction.readonly_manytoone_master
  - composite_readonly_manytoone_transaction.composite_readonly_manytoone_master
